services:
    nginx:
        image: nginx:stable-alpine
        restart: unless-stopped
        ports:
            - '8090:80'
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/var/www/chat
        depends_on:
            - db
    app:
        ports:
            - '9999:9000'
            - '6001:6001'
        restart: unless-stopped
        build:
            context: docker/php
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./:/var/www/chat
    db:
        image: postgres:latest
        ports:
            - '5462:5432'
        env_file:
            - docker/pgsql/pgsql.env
        volumes:
            - db_data:/var/lib/postgresql@14/data:rw
volumes:
    db_data: